### ISSUE TITLE
Issue with pulling and pushing causing device to crash

### ISSUE THREAD

**Issue by LivingSynthesis** [Unreal-Dan/lightshow.lol#11] opened 2024-06-04 02:31 UTC
Pulling or pushing repeatedly and rapidly will cause the device to crash (tested on orbit). I propose introducing a short cooldown on that functionality.

**Comment by Unreal-Dan** [comment] 2024-08-05 03:49
cannot reproduce on latest lightshow.lol, some changes to vortexport happened which might have fixed this. closing for now

**Closed by Unreal-Dan** 2024-08-05 03:49 UTC
Labels: bug, good first issue
