### ISSUE TITLE
[needs example] Cannot pull from devices with complex mode settings

### ISSUE THREAD

**Issue by LivingSynthesis** [Unreal-Dan/lightshow.lol#5] opened 2024-05-30 01:29 UTC
Saves with different modes on each led cannot be pulled.
for instance if one LED is hyperstrobe and the others are strobe, this will not pull. (tested on orbit 28 leds)

In addition, sometimes after changing the default modes, pushing and pulling will work, but if you alternate between pushing and pulling it will eventually crash (I think usually when pulling)

**Comment by Unreal-Dan** [comment] 2024-06-22 03:58
need to provide an example save, just export it, I was able to pull this fine:

`{"flags":2,"num_leds":28,"single_pats":[{"args":[20,43,0,0,0],"colorset":["0x00ff42","0x005532","0x0015ff","0x550041","0xff006f"],"flags":0,"numColors":5,"pattern_id":0},{"args":[4,7,23,26,0],"colorset":["0xe7ff00","0x000d55","0x000354","0x1200ff","0x544900"],"flags":0,"numColors":5,"pattern_id":0},{"args":[7,59,0,0,0,5,0],"colorset":["0x002654","0x0075ff","0x542f00","0x0075ff","0x002654"],"flags":0,"numColors":5,"pattern_id":25},{"args":[9,6,31,0,3,8,2],"colorset":["0x7e00ff","0x2a0055","0xff8400","0x00552a"],"flags":0,"numColors":4,"pattern_id":25},{"args":[10,5,21,29,0],"colorset":["0x002a16","0x003454","0x1b007e","0xa800a0","0xd20016","0xfcc300"],"flags":0,"numColors":6,"pattern_id":0},{"args":[9,6,31,0,3,8,2],"colorset":["0x7e00ff","0x2a0055","0xff8400","0x00552a"],"flags":0,"numColors":4,"pattern_id":25},{"args":[10,5,21,29,0],"colorset":["0x002a16","0x003454","0x1b007e","0xa800a0","0xd20016","0xfcc300"],"flags":0,"numColors":6,"pattern_id":0},{"args":[9,6,31,0,3,8,2],"colorset":["0x7e00ff","0x2a0055","0xff8400","0x00552a"],"flags":0,"numColors":4,"pattern_id":25},{"args":[20,43,0,0,0],"colorset":["0x00ff42","0x005532","0x0015ff","0x550041","0xff006f"],"flags":0,"numColors":5,"pattern_id":0},{"args":[4,7,23,26,0],"colorset":["0xe7ff00","0x000d55","0x000354","0x1200ff","0x544900"],"flags":0,"numColors":5,"pattern_id":0},{"args":[4,7,23,26,0],"colorset":["0xe7ff00","0x000d55","0x000354","0x1200ff","0x544900"],"flags":0,"numColors":5,"pattern_id":0},{"args":[20,43,0,0,0],"colorset":["0x00ff42","0x005532","0x0015ff","0x550041","0xff006f"],"flags":0,"numColors":5,"pattern_id":0},{"args":[8,49,0,0,0],"colorset":["0xffc5b2","0x0d1119","0xffc5b2"],"flags":0,"numColors":3,"pattern_id":0},{"args":[1,10,0,0,0],"colorset":["0xff0000","0x00ff00","0x0000ff","0xabaa00","0x5500ab"],"flags":0,"numColors":5,"pattern_id":4},{"args":[3,9,29,29,0,3,0],"colorset":["0x352be7"],"flags":0,"numColors":1,"pattern_id":25},{"args":[3,9,29,29,0,3,0],"colorset":["0x352be7"],"flags":0,"numColors":1,"pattern_id":25},{"args":[20,43,0,0,0],"colorset":["0x00ff42","0x005532","0x0015ff","0x550041","0xff006f"],"flags":0,"numColors":5,"pattern_id":0},{"args":[20,43,0,0,0],"colorset":["0x00ff42","0x005532","0x0015ff","0x550041","0xff006f"],"flags":0,"numColors":5,"pattern_id":0},{"args":[20,43,0,0,0],"colorset":["0x00ff42","0x005532","0x0015ff","0x550041","0xff006f"],"flags":0,"numColors":5,"pattern_id":0},{"args":[20,43,0,0,0],"colorset":["0x00ff42","0x005532","0x0015ff","0x550041","0xff006f"],"flags":0,"numColors":5,"pattern_id":0},{"args":[4,7,23,26,0],"colorset":["0xe7ff00","0x000d55","0x000354","0x1200ff","0x544900"],"flags":0,"numColors":5,"pattern_id":0},{"args":[8,49,0,0,0],"colorset":["0xffc5b2","0x0d1119","0xffc5b2"],"flags":0,"numColors":3,"pattern_id":0},{"args":[8,49,0,0,0],"colorset":["0xffc5b2","0x0d1119","0xffc5b2"],"flags":0,"numColors":3,"pattern_id":0},{"args":[20,43,0,0,0],"colorset":["0x00ff42","0x005532","0x0015ff","0x550041","0xff006f"],"flags":0,"numColors":5,"pattern_id":0},{"args":[4,7,23,26,0],"colorset":["0xe7ff00","0x000d55","0x000354","0x1200ff","0x544900"],"flags":0,"numColors":5,"pattern_id":0},{"args":[8,49,0,0,0],"colorset":["0xffc5b2","0x0d1119","0xffc5b2"],"flags":0,"numColors":3,"pattern_id":0},{"args":[3,9,29,29,0,3,0],"colorset":["0x352be7"],"flags":0,"numColors":1,"pattern_id":25},{"args":[8,49,0,0,0],"colorset":["0xffc5b2","0x0d1119","0xffc5b2"],"flags":0,"numColors":3,"pattern_id":0}]}`

**Comment by Unreal-Dan** [comment] 2024-08-05 04:42
closing as cannot reproduce for now

**Closed by Unreal-Dan** 2024-08-05 04:42 UTC
Labels: bug
